"""create products table

Revision ID: 05f0696ceb47
Revises: 0744e81ba088
Create Date: 2026-07-28 12:27:48.487342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05f0696ceb47'
down_revision: Union[str, Sequence[str], None] = '0744e81ba088'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('stock_quantity', sa.Integer(), nullable=False))
    op.alter_column('products', 'category',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=True)
    op.alter_column('products', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_column('products', 'unit')
    op.drop_column('products', 'quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('unit', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.alter_column('products', 'description',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('products', 'category',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('products', 'stock_quantity')
    # ### end Alembic commands ###
