"""add appointment end time

Revision ID: 4626b74679a8
Revises: 5b0c7ad0d4c9
Create Date: 2026-07-26 15:45:30.529131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4626b74679a8'
down_revision: Union[str, Sequence[str], None] = '5b0c7ad0d4c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        "appointments",
        sa.Column(
            "end_time",
            sa.DateTime(),
            nullable=True,
        ),
    )

    op.execute(
        """
        UPDATE appointments
        SET end_time = appointment_time
        """
    )

    op.alter_column(
        "appointments",
        "end_time",
        nullable=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'end_time')
    # ### end Alembic commands ###
