"""add employee and service to appointments

Revision ID: 5b0c7ad0d4c9
Revises: 76682185c60a
Create Date: 2026-07-26 15:22:57.589223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b0c7ad0d4c9'
down_revision: Union[str, Sequence[str], None] = '76682185c60a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('employee_id', sa.Integer(), nullable=False))
    op.add_column('appointments', sa.Column('service_id', sa.Integer(), nullable=False))
    op.alter_column('appointments', 'notes',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_appointments_id'), 'appointments', ['id'], unique=False)
    op.create_foreign_key(None, 'appointments', 'employees', ['employee_id'], ['id'])
    op.create_foreign_key(None, 'appointments', 'services', ['service_id'], ['id'])
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_index(op.f('ix_appointments_id'), table_name='appointments')
    op.alter_column('appointments', 'notes',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.drop_column('appointments', 'service_id')
    op.drop_column('appointments', 'employee_id')
    # ### end Alembic commands ###
