"""remove employee salary default

Revision ID: d54a2fbb4e65
Revises: f2b35ed0bf6f
Create Date: 2026-08-02 22:34:19.057765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd54a2fbb4e65'
down_revision: Union[str, Sequence[str], None] = 'f2b35ed0bf6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
