"""add stock deducted to invoices

Revision ID: f2b35ed0bf6f
Revises: 5eb2308180ff
Create Date: 2026-07-30 19:30:53.942327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2b35ed0bf6f'
down_revision: Union[str, Sequence[str], None] = '5eb2308180ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('stock_deducted', sa.Boolean(), nullable=False, server_default=sa.false(),))
    op.alter_column('invoices', 'stock_deducted', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'stock_deducted')
    # ### end Alembic commands ###
